api/urls.py
from django.urls import path
from . import views
app_name = 'api'
urlpatterns = [
    # path('all/posts/', views.posts_list, name='all-posts'),
    # path('contact/<int:pk>/', views.ContactView.as_view(), name='all-contact'),
    path('contact/', views.ContactApiView.as_view()),
    path('posts/<int:pk>/', views.PostApiView.as_view()),
    path('posts/', views.PostApiView.as_view()),
    path('list/posts/', views.PostApiListView.as_view()),
    path('detail/posts/<int:pk>', views.PostApiDetailView.as_view()),
    # path('posts/<int:pk>/', views.PostApiDetail.as_view(), name='all-posts'),
    # path('detail/posts/<pk>/', views.post_detail, name='detail-posts'),

    # path('one/posts/<int:pk>/', views.one_posts, name='one-posts'),
    # path('delete/posts/<int:pk>/', views.delete_post, name='delete-posts'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('category/', include('category.urls', namespace='category')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token)

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'home'
urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='home/index.html'), name="about"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.SignupView.as_view(), name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('search/', views.SearchView.as_view(), name="search-url"),
    # path('save/contact/', views.save_contact, name="save-contact"),
]

posts/urls.py
from django.urls import path


from posts import views


app_name = 'posts'
urlpatterns = [
    path('get/<slug:slug>/', views.PostDetail.as_view(), name='posts-get'),
    path('forms/', views.PostCreateView.as_view(), name="posts-form"),
    path('delete/<slug>/', views.PostDeleteView.as_view(), name="posts-delete"),
    path('update/<slug>/', views.PostUpdateView.as_view(), name="posts-update"),
    # path('update/<slug>/', views.PostUpdateView.as_view(), name="posts-update"),
]

templates/components/navbar/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">    
        <a class="navbar-brand" href="{% url 'home:home' %}">Blog</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
                </li>


                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:logout' %}">logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:posts-form' %}">Create Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:profile' %}">Hi {{ request.user | title }}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:register' %}">Register</a>
                    </li>
                {% endif %}
                
            </ul>

            
            <form class="d-flex" action="{% url 'home:search-url' %}" method="get">
                <input class="form-control me-2" type="search" name="q" placeholder="Search" required aria-label="Search">
                <button class="btn btn-outline-success "type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>